---
- name: 0.系统初始化
  gather_facts: no
  hosts: 
    - lnmp
  roles:
    - common
  tags: common

- name: 2.部署mysql
  gather_facts: no
  hosts:
    - mysql
  roles:
    - mysql
  tags: mysql


- name: 3.部署PHP
  gather_facts: no
  hosts:
    - php
  roles:
    - php
  tags: php
