---
lib_packages:
  - gd
  - gd-devel
  - autoconf
  - libjpeg
  - libjpeg-devel
  - libpng
  - libpng-devel
  - freetype
  - freetype-devel
  - libxml2
  - libxml2-devel
  - zlib
  - zlib-devel
  - libzip
  - libzip-devel
  - glibc
  - glibc-devel
  - glib2
  - glib2-devel
  - bzip2
  - bzip2-devel
  - curl
  - curl-devel
  - openssl
  - openssl-devel
  - openldap
  - openldap-devel
  - libtool
  - libtool-ltdl-devel
  - c-ares
  - mhash
  - libmhash
  - mcrypt
  - libmcrypt
  - libmcrypt-devel
  - sqlite
  - sqlite-devel
  - oniguruma
  - oniguruma-devel
