---
- name: 设置主机名
  raw: hostnamectl set-hostname {{host_name}} &&
       hostname {{host_name}}

- name: 添加hosts
  template: src=hosts.j2 dest=/etc/hosts

- name: 配置DNS
  template: src=resolv.conf.j2 dest=/etc/resolv.conf

- name: 关闭firewalld
  service: name=firewalld state=stopped enabled=no
  
- name: 关闭selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"
    
- name: 拷贝时区
  copy: src=/usr/share/zoneinfo/Asia/Shanghai dest=/etc/localtime 

- name: 安装epel源和iptables-services
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - iptables-services
    - epel-release

- name: 创建解压目录
  file: dest={{ lnmp_src_dir }} state=directory
